export const toolDescriptionLines: readonly string[] = [
	"Compute a partial Bazi chart when the birth hour is unknown. Requires year/month/day/gender. Use this when the caller knows only the birth date.",
	"",
	"How it works:",
	"- Internally calls upstream `shunshi-bazi-core` with a placeholder hour of 12:00 (noon) — chosen to stay far from the 23:00 子时 day-pillar boundary so the year/month/day pillars are stable.",
	"- All time-pillar fields and time-dependent derivations are then either stripped, set to `null`, or recomputed without the time pillar. See `meta.disclaimer` in the response for the per-field treatment.",
	"",
	"Output differences vs `getBaziChart`:",
	"- `八字.柱位详细` contains only `年柱`, `月柱`, `日柱` — the `时柱` key is **omitted entirely** (not just nulled). Identify the day-pillar via `日柱.isDayMaster === true`.",
	"- `八字.命宫`, `八字.身宫`, `八字.胎元`, `八字.胎息` are all `null` — these formulas require the birth hour and cannot be approximated.",
	"- `真太阳时` is **omitted** from the response (true-solar-time correction is meaningless without a real hour).",
	"- `输入.公历` is a date-only string (`YYYY-MM-DD`); `八字.公历` is the same date. No time component is exposed because none was provided.",
	"- `输入` does not echo back `城市`, `经度`, `纬度` — partial mode does not accept these inputs.",
	"- `输入.时辰` is `null`.",
	"- `八字.十神统计` is recomputed: `透` counts only `年柱.主星 + 月柱.主星`; `藏` counts only `年/月/日柱.副星`. Time-pillar contributions are excluded.",
	"- `八字.柱间关系` is filtered to drop any pair/triple involving the time pillar — only relations among 年/月/日 remain.",
	"- `八字.刑冲合会` (the upstream raw flat list) is **kept as-is** for compatibility but may still mention relations involving the placeholder time pillar — prefer the filtered `八字.柱间关系` instead.",
	"- `八字.决策辅助.日主根气` is recomputed using only 3 pillars (年/月/日 地支 藏干). `透藏平衡` automatically reflects the new `十神统计`. `日主得令` is unchanged (it depends only on the month pillar).",
	"- `八字.五行分值` is recomputed: time-pillar 天干 (1.0) and time-pillar 藏干 (1.0/0.5/0.3) contributions are removed; `占比` is renormalised over the 3-pillar total.",
	"- `八字.大运` is **kept** because the decade-cycle direction (顺/逆) depends only on year-pillar polarity + gender — both unaffected by hour. **However**, the precise 起运 string and 起运日期 are calculated from the distance between birth time and the next/previous solar term, so they may carry **±1 day to ±1-2 month error** when the hour is unknown — and the resulting `起始年份` / `结束年份` may shift by ±1 year. Treat decade boundaries as approximate windows, not precise dates. See `meta.disclaimer.大运起运精度`.",
	"- `八字.流年` is unchanged — 流年 derivation depends only on the day-master stem and Gregorian year, neither of which needs the hour.",
	"- `八字.旬空` (`日柱旬空`, `年柱旬空`) and per-pillar `所在旬空亡` / `落空亡` are unchanged in semantics — at noon the day pillar is identical to what it would be without solar-time correction, so 旬空 reference branches are stable.",
	"- All time strings that survive (`输入.公历`, `八字.公历`) are date-only `YYYY-MM-DD`. `meta.referenceDateUsed` is unchanged from full mode.",
	"",
	"Inherited from `getBaziChart` (unchanged behaviour):",
	'- `八字.柱位详细.日柱.主星` is `null` (日主 carries no ten-god against itself); use `日柱.isDayMaster === true` to identify the day pillar; `日柱.label` is `"日主"`.',
	'- `八字.大运[].日主关系` is `null` when there is no relation (instead of `""`).',
	"- `八字.大运[].当前` is computed from `meta.referenceDateUsed` (defaults to today). Override via the `referenceDate` input.",
	"- `meta.scoringMethod` documents how `八字.五行分值` is computed (3-pillar variant).",
	"- `meta.disclaimer` enumerates exactly which fields were stripped, nulled, or recomputed and why — surface this to the user when explaining the chart's confidence level.",
] as const;
