export const toolDescriptionLines: readonly string[] = [
	"Compute a three-pillar Bazi chart when the birth hour is unknown. Requires year/month/day/gender. Use this when the caller knows only the birth date.",
	"",
	"How it works:",
	"- The chart is built natively from 年/月/日 alone. No placeholder hour is invented, so nothing in the output is derived from a time that was never supplied.",
	"- 年柱 and 月柱 use day-granular attribution: the whole calendar day on which a 節 falls belongs to the new month (and 立春 day to the new 干支年).",
	"- When the birth date is itself a 節 day the answer is genuinely undetermined, and `八字.节气歧义` reports both candidates instead of hiding the choice. See below.",
	"",
	"`八字.节气歧义` (only field with no counterpart in `getBaziChart`):",
	"- `null` on ordinary days. Non-null on the ~1.6% of dates that carry a 節.",
	"- `节气` is the term name, `时刻` its exact local moment (`YYYY-MM-DDTHH:MM:SS`), `影响` lists which pillars actually differ across it.",
	"- `此刻之前` holds the 年柱/月柱 for a birth earlier that day; `此刻之后` holds them for a birth at or after the moment. `此刻之后` is what the rest of the response uses.",
	"- If the caller can narrow the birth time to one side of `时刻`, prefer the matching branch and say so; otherwise present both.",
	"",
	"Output differences vs `getBaziChart`:",
	"- `八字.三柱` replaces `八字.四柱` and holds exactly three 干支.",
	"- `八字.柱位详细` contains only `年柱`, `月柱`, `日柱` — the `时柱` key is **omitted entirely** (not just nulled). Identify the day-pillar via `日柱.isDayMaster === true`.",
	"- `八字.命宫`, `八字.身宫`, `八字.胎元`, `八字.胎息` are all `null` — these formulas require the birth hour and cannot be approximated.",
	"- `真太阳时` is **omitted** from the response, and `城市` / `经度` / `纬度` are not accepted as inputs: the correction only ever moves the hour pillar.",
	"- `输入.公历` and `八字.公历` are date-only (`YYYY-MM-DD`); `输入.时辰` is `null`; `八字.农历` carries no 时辰 suffix.",
	"- `八字.十神统计`, `八字.五行分值`, `八字.刑冲合会`, `八字.柱间关系` and `八字.决策辅助.日主根气` all cover 年/月/日 only. `占比` in `八字.五行分值` is normalised over the 3-pillar total.",
	"- `八字.大运` is **kept**: the decade-cycle direction (顺/逆) depends only on year-pillar polarity + gender, neither of which needs the hour. **However**, 起运 and 起运日期 are measured from the birth moment to the neighbouring solar term, and the reference moment used here is the midpoint of the day's month-command window, so they may carry **±1 day to ±1-2 month error** — and the resulting `起始年份` / `结束年份` may shift by ±1 year. Treat decade boundaries as approximate windows, not precise dates. See `meta.disclaimer.大运起运精度`.",
	"- `八字.流年` is unchanged — 流年 derivation depends only on the day-master stem and the 干支年, neither of which needs the hour.",
	"- `八字.旬空` (`日柱旬空`, `年柱旬空`) and per-pillar `所在旬空亡` / `落空亡` are unchanged in semantics; the day pillar does not depend on the hour except across the 23:00 子时 switch, which no date-only input can reach.",
	"",
	"Inherited from `getBaziChart` (unchanged behaviour):",
	'- `八字.柱位详细.日柱.主星` is `null` (日主 carries no ten-god against itself); use `日柱.isDayMaster === true` to identify the day pillar; `日柱.label` is `"日主"`.',
	'- `八字.大运[].日主关系` is `null` when there is no relation (instead of `""`).',
	"- `八字.大运[].当前` is computed from `meta.referenceDateUsed` (defaults to today). Override via the `referenceDate` input.",
	"- `meta.scoringMethod` documents how `八字.五行分值` is computed (3-pillar variant).",
	"- `meta.disclaimer` enumerates exactly which fields are absent, null, or 3-pillar-only and why — surface this to the user when explaining the chart's confidence level.",
] as const;
